### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by karl-project-review** [usman7vt/intro-data-capstone-musclehub#4]
(Meets Expectations)

Good work with this project! Your code performs all of the necessary calculations and produces appropriate graphs. What's more, your graphs are well-labeled and use colors effectively. 

Your report uses your visualizations effectively to help us understand the data, and you explain the test setup clearly. However, it would be useful to include a mention of the p-values and the level of significance used in this study, as this would give readers a better sense of how confident we are in the conclusions presented. Also, be careful of wording in the conclusions, as the third and fourth bullet points refer to "those who take [or do not take] the fitness test" as opposed to "applicants who take [or do not take] the fitness test," which gives the impression that those bullet points directly contradict the final point that those who do not take a fitness test are more likely to purchase a membership. It is a good practice to proofread reports to look for wording issues like this that can make our conclusions unclear.

If you would like any additional practice, think about how we might design a study to test what (if any) effect requiring the fitness test has on MuscleHub's overall profitability as opposed to just initial membership purchases. What additional data would we need to collect? How feasible do you think such a study would be?

Again, well done!

**Comment by usman7vt** [comment]
Hello Karl,

Thank you for reviewing my project. Through out the entire course I have learned a lot but I believe I need to practice again and again to achieve perfection.  I will definitely revisit issues you have pointed out.  I could not agree with you any more that conducting analysis is one thing however explaining it visually is another. 

The wording we use truly matters, thanks for bringing it to my attention. I assume the more projects and analysis I will conduct it will give me a better sense of how I shall approach my conclusions and avoid causing any confusion for the viewers.

I will definitely look in to what other forms of data can we possibly gather in relation to the above project and what other analysis can be performed. Again I strongly believe I need to revisit all the project which I completed as part of this intensive course so I could truly benefit from the entire content. 

As a matter of fact I am now considering to pursue the other capstone project on Biodiversity to help increase my learning. I want to continue my learning and pursue track of a data scientist. If you have any recommendations please feel free to share. Thank you

Regards,
Usman

**Comment by usman7vt** [comment]
Hello Karl,

I have not yet received my certificate of completion yet, can you please tell when would that happen.

Regards,
Usman

**Comment by karl-project-review** [comment]
Hello Usman,

It should be within two weeks after the official end date of your course. I don't know which cohort you are in, so I cannot give you an exact date, but I am including a link to the FAQ page addressing this:
https://help.codecademy.com/hc/en-us/articles/360000386153-When-will-I-receive-my-credential-for-completing-a-Pro-Intensive-
If you have completed all of the course material but still have not received your certificate two full weeks after the official end date for your cohort, you may want to contact customer service to ask about this. 
 
Cheers,
Karl

**Comment by usman7vt** [comment]
Thank you Karl!

Best,
Usman
